env:
  browser: true
  es6: true
  node: true
  jquery: true
  mocha: true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/essential'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - mocha
  - vue
rules:
  semi: ['warn', 'always']

  # Mocha plugin rules
  mocha/no-exclusive-tests: ['error']
  mocha/no-identical-title: ['error']
  mocha/no-skipped-tests: ['error']
